image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  DOCKER_HOST: tcp://localhost:2375  
  DOCKER_DRIVER: overlay2

build-branch:
  stage: build
  variables:
    IMAGE_URI: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_NAME-$CI_JOB_ID
  only:
    - branches
    - master
  script:
  - docker build -t $IMAGE_URI .
  - docker push $IMAGE_URI

build-tag:
  stage: build
  variables:
    IMAGE_URI: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  script:
  - docker build -t $IMAGE_URI .
  - docker push $IMAGE_URI
  
deploy:tagged-image:
  stage: deploy
  services:
    - docker:dind
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://localhost:2375
    IMAGE_URI: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  before_script:
    - docker login -u $PUBLISH_USERNAME -p $PUBLISH_PASSWORD $PUBLISH_REGISTRY
  script:
    - docker pull $IMAGE_URI
    - docker tag $IMAGE_URI ${PUBLISH_REGISTRY}/${PUBLISH_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${PUBLISH_REGISTRY}/${PUBLISH_IMAGE}:${CI_COMMIT_TAG}

